/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AttendeesRouteImport } from './routes/attendees'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeesRoute = AttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/attendees': typeof AttendeesRoute
  '/events': typeof EventsRoute
}
export interface FileRoutesByTo {
  '/attendees': typeof AttendeesRoute
  '/events': typeof EventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/attendees': typeof AttendeesRoute
  '/events': typeof EventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/attendees' | '/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/attendees' | '/events'
  id: '__root__' | '/attendees' | '/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AttendeesRoute: typeof AttendeesRoute
  EventsRoute: typeof EventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendees': {
      id: '/attendees'
      path: '/attendees'
      fullPath: '/attendees'
      preLoaderRoute: typeof AttendeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AttendeesRoute: AttendeesRoute,
  EventsRoute: EventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
